FROM node:20-alpine as base

ARG AWS_ACCESS_KEY_ID
ARG AWS_REGION
ARG AWS_SECRET_ACCESS_KEY
ARG NEXT_PUBLIC_GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG JWE_SECRET
ARG DYNAMO_PROMPT
ARG DYNAMO_USER
ARG S3_PROMPT
ARG LAMBDA_DALLE_SAVE_HISTORY
ARG OPENAI_API_KEY

# Dependency layer
FROM base as deps
# RUN apk add --no-cache libc6-compat
RUN npm install -g npm@10.2.3

WORKDIR /netizen
COPY package*.json ./
RUN npm ci

# Build layer
FROM base as builder
WORKDIR /netizen
COPY --from=deps /netizen/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED 1

ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
ENV AWS_REGION $AWS_REGION
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID $NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET $GOOGLE_CLIENT_SECRET
ENV JWE_SECRET $JWE_SECRET
ENV DYNAMO_PROMPT $DYNAMO_PROMPT
ENV DYNAMO_USER $DYNAMO_USER
ENV S3_PROMPT $S3_PROMPT
ENV LAMBDA_DALLE_SAVE_HISTORY $LAMBDA_DALLE_SAVE_HISTORY
ENV OPENAI_API_KEY $OPENAI_API_KEY

RUN npx nx reset
RUN npx nx run internal-website:build --configuration=production

# Runner layer
FROM base AS runner
WORKDIR /netizen

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /netizen/dist/apps/internal/website/.next/standalone ./
COPY --from=builder /netizen/dist/apps/internal/website/.next/static ./dist/apps/internal/website/.next/static

RUN chown nextjs:nodejs /netizen

USER nextjs

EXPOSE 3000

ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
ENV AWS_REGION $AWS_REGION
ENV NEXT_PUBLIC_GOOGLE_CLIENT_ID $NEXT_PUBLIC_GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET $GOOGLE_CLIENT_SECRET
ENV JWE_SECRET $JWE_SECRET
ENV DYNAMO_PROMPT $DYNAMO_PROMPT
ENV DYNAMO_USER $DYNAMO_USER
ENV S3_PROMPT $S3_PROMPT
ENV LAMBDA_DALLE_SAVE_HISTORY $LAMBDA_DALLE_SAVE_HISTORY
ENV OPENAI_API_KEY $OPENAI_API_KEY

RUN mkdir /home/nextjs/.aws
RUN echo "[default]" > /home/nextjs/.aws/credentials
RUN echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> /home/nextjs/.aws/credentials
RUN echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> /home/nextjs/.aws/credentials

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["node", "./apps/internal/website/server.js"]