name: Internal cdk workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  nanikore-cdk:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Environment - ${{ inputs.environment }}
        run: |
          echo ${{ inputs.environment }}
          echo ${{ vars.TARGET }}
      - name: Git clone repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          role-session-name: github-actions-session
          aws-region: ap-southeast-1
      - run: npm ci
      - run: npx nx run internal-formation:deploy --args="--target=${{vars.TARGET}}"
        env:
          TARGET: ${{vars.TARGET}}
