on:
  push:
    branches:
      - release/nanikore-staging-website

permissions:
  id-token: write
  contents: read

jobs:
  nanikore-staging-website:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          role-session-name: github-actions-session
          aws-region: ap-southeast-1
      - name: Setup Lightsail
        run: |
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "lightsailctl"
          sudo mv "lightsailctl" "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl
      - run: npm ci
      - run: npx nx run nanikore-docker:build-image
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ap-southeast-1
          COGNITO_CLIENT_ID: ${{vars.COGNITO_CLIENT_ID}}
          COGNITO_CLIENT_SECRET: ${{secrets.COGNITO_CLIENT_SECRET}}
          COGNITO_USERPOOL_ID: ${{vars.COGNITO_USERPOOL_ID}}
          DYNAMO_EVENTS: ${{vars.DYNAMO_EVENTS}}
          DYNAMO_PROJECTS: ${{vars.DYNAMO_PROJECTS}}
          DYNAMO_SURVEY_MODELS: ${{vars.DYNAMO_SURVEY_MODELS}}
          DYNAMO_SURVEYS: ${{vars.DYNAMO_SURVEYS}}
          DYNAMO_PROFILES: ${{vars.DYNAMO_PROFILES}}
          DYNAMO_TRANSACTIONS: ${{vars.DYNAMO_TRANSACTIONS}}
          NEXTAUTH_URL: ${{vars.NEXTAUTH_URL}}
          NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
          NEXT_PUBLIC_COGNITO_SIGNOUT_URL: ${{vars.NEXT_PUBLIC_COGNITO_SIGNOUT_URL}}
      - name: Push image to lightsail
        run: |
          aws lightsail push-container-image --region ap-southeast-1 --service-name ${{vars.LIGHTSAIL_SERVICE_NAME}} --label latest --image nanikore-website:latest
          aws lightsail get-container-images --service-name ${{vars.LIGHTSAIL_SERVICE_NAME}} | jq --raw-output ".containerImages[0].image" > image.txt
          jq --arg image $(cat image.txt) '.containers.app.image = $image' apps/nanikore/docker/container.template.json > container.json
          aws lightsail create-container-service-deployment --service-name ${{vars.LIGHTSAIL_SERVICE_NAME}} --cli-input-json file://$(pwd)/container.json
